### ISSUE TITLE
Improve sample ingestion speed for Selector

### ISSUE THREAD

**Issue by vGsteiger** [eth-easl/modyn#204]
Our sample ingestion speed for the SelectorstateMetadata is too slow. We need to improve that.  (If it turns out to work great, we should do these tricks at storage as well)

After talking to Chris Engelbert from Timescale, we should proceed with vanilla postgres for now. Timescale always partitions by time and postgres apparently supports partitioning similar to timescale's space partitioning. Timescale might be used if postgres is still too slow and we need multi-node support or other ideas, as outlined at the end of this issue.

- [x] Step 1: Remove the selector_state_metadata_id primary key and use (pipeline_id, sample_key) as compound primary key. There is no need for the unique ID and it enforces generation of serialized ints which might slow down the process.

- [x] Step 2: Remove the foreign key constraint on pipeline_id. We can be sure this is valid, but having this foreign key will slow down inserts as the integrity has to be checked. Also remove nullable from pipeline_id to avoid another integrity check.

- [x] Step 3: Always make sure to use a tuned postgres setup (see #185 - we should fix #185 in this context such that we do not forget about this)

- [x] Step 4: Use postgres hash based partitioning. [Here](https://www.dcodeman.com/working-with-hash-partitions-in-postgresql/) is a good guide. We need to setup a main table and then partition subtables. The number of sub-partitions should be configurable and can be 32 or 64, for example. Unfortunately, the partition tables need to be created manually. We need to figure out how to do this with sqlalchemy. We should also check out the hash function postgres uses and which key (hopefully the compound primary key) it uses for hashing. (Implemented in #209)

- [ ] Step 5: We can also use postgres tablespaces. This means that the different tables live on different disks. For example, we can have 32 partitions on SSD 1 and 32 partitions on SSD 2 to parallelize further.

- [x] Step 6: (We did this for EuroMLSys already). Set all partitions to UNLOGGED:

```
    __table_args__ = (
        Index("ssm_pipeline_seen_idx", "pipeline_id", "seen_in_trigger_id"),
        {"extend_existing": True, "prefixes": ["UNLOGGED"]},
    )
```
(Implemented in #209)

- [x] ~~Step 7: Delete index and re-create after insert. We should remove all indices from the table and add the index (concurrently, i.e., in the background) after inserting all data from the trigger. Unfortunately, postgres does not support pausing of indices (only in using them, not in building them). However, apparently creating an index afterwards is significantly faster than updating it. Furthermore we currently index on the pipeline id, we should do the same thing there. (Part of #220)~~ not relevant anymore, the index is what we partition by anyways

Step 8: If all of this still is very slow, we might want to check out if we can somehow upload the data, e.g., via FTP or so and use pgdump or COPY or so to import the CSV data into the DB. This is apparently also more optimized than batched inserts.

Step 9: Try disabling postgres JIT compiler.

---- Optional: How to use Timescale? ----

We could store when the first notification of data inserts happen and when the last happened and store these timestamps as the time dimension for Timescale. This could be the time dimension. Then we add pipeline ID and other stuff as space dimensions and multi-node behavior.

**Comment by vGsteiger** [comment]
I think we can close this with the addition of #262? @MaxiBoether

**Comment by MaxiBoether** [comment]
yeah, I guess #262 is sufficient. Let's close this for now
