### ISSUE TITLE
Tests and linting

### ISSUE THREAD

**Issue by MaxiBoether** [eth-easl/modyn#29]
We want to have at least somewhat good test coverage and implement a coherent coding style. Hence, we should do the following:

- [x] Enable Python unit tests in CI, including a coverage report.
- [ ] Enable failing on coverage that is too low, partially introduced by #42, should be finalized with #51
- [x] ~~Can we test protobuf files (for validity) as well?~~ I decided I don't care about this for now.
- [x] Enable Flake8 code styling check in CI
- [x] Enable Pylint in CI (#37), partially introduced by #42, should be finalized with #34
- [x] Enable isort in CI (solved by #71)
- [x] Enable black in CI (solved by #71)
- [x] Find how to run tests for other, non-Python components, such as Docker containers etc. (we test the Docker container + docker-compose setup now by #67)
- [x] Enable system-level tests for integration of both Python and non-Python components, i.e., entire workflows (enabled via #67)
- [x] Enable mypy in CI (#30, closed by #40)

The idea is to converge into the currently discussed architecture and then enable this, after the file structure is settled.

The following issues are sub-issues of this overarching issue:

- [x] #11 
- [x] #20 
- [x] #21 
- [x] #23 
- [x] #24 
- [x] #25 
- [x] #26
